config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :registrations, only: [ :new, :create ]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  #
  #
  root "page#home"
  get "home", to: "page#home"


  get "components", to: "page#components"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  validates :email_address, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
  validates :password, presence: true

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      flash[:alert] = "You must be logged in to access this page."
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    flash.now[:notice] = "Welcome to the home page!"
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  allow_unauthenticated_access only: %i[new create]
  before_action :resume_session, only: :new

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to root_path, notice: "You've successfully signed up to CosmosJob. Welcome!"
    else
      flash[:alert] = @user.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.expect(user: [ :email_address, :password, :password_confirmation, :first_name, :last_name ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/svg_helper.rb
# frozen_string_literal: true

module SvgHelper
  def svg_tag(icon_name, options = {})
    file = Rails.root.join("app", "assets", "images", "icons", "#{icon_name}.svg").read
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css "svg"

    options.each { |attr, value| svg[attr.to_s] = value }

    doc.to_html.html_safe # rubocop:disable Rails/OutputSafety
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Eight Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <%= render "shared/head" %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%= render "shared/navbar" %>
  <body>
    <%= yield %>
  </body>

  <%= turbo_frame_tag :flashes do %>
    <%= render "shared/flashes" %>
  <% end %>

  <%= render "shared/footer" %>
</html>

app/views/page/home.html.erb
  <div class="container">
    <header>
      <h1>Welcome to the Cosmos</h1>
    </header>
    
    <section id="hero">
      <h2>Explore the Universe of My Work</h2>
      <p>Dive into my portfolio and discover stellar projects.</p>
      <%= render(Common::Button::BtnComponent.new(builder: 'default', style: 'primary', right_icon: 'cube')) do %>
        View project
      <% end %>
    </section>

    <section id="about">
      <h2>About Me</h2>
      <p>I'm a space enthusiast and developer who loves to build cosmic experiences on the web.</p>
    </section>


    <section id="projects">
      <h2>Projects</h2>

      <div class="project">
        <h3>Galaxy Explorer</h3>
        <p>An interactive map of the Milky Way.</p>
      </div>
      <div class="project">
        <h3>Rocket Simulator</h3>
        <p>A physics-based rocket launching game.</p>
      </div>
    </section>

    <section id="contact">
      <h2>Contact</h2>
      <p>Reach out if you'd like to collaborate on interstellar projects!</p>
      <a href="mailto:space.dev@example.com" class="btn">Email Me</a>
    </section>  
  </div>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <%= render(Common::Flash::FlashComponent.new(type: type, message: message)) %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; 2024 Space Portfolio. All rights reserved.</p>
</footer>

app/views/shared/_head.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

app/views/shared/_navbar.html.erb
<nav>
  <% if Current.user.present? %>
    <div class="d-flex gap-4 align-items-center">
      <%= link_to "Home", root_path, class: "btn btn-primary" %>
      <%= link_to "About", "#", class: "btn btn-secondary" %>
      <%= link_to "Contact", "#", class: "btn btn-secondary" %>
      <%= render Common::Button::BtnComponent.new(
        builder: "link_to",
        path: session_path,
        method: :delete,
        style: "light",
        other_styles: "ms-auto",
        data: { turbo_method: :delete }
      ) do %>
        Sign out
      <% end %>
    </div>
  <% else %>
    <div class="d-flex gap-2">
      <%= link_to "Sign in", "#", class: "btn btn-primary" %>
      <%= link_to "Sign up", new_registrations_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</nav>